version: "3.9"
services:
  db:
    image: "postgres"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
